### ISSUE TITLE
Add generic types

### ISSUE THREAD

**Issue by josephluck** [harrygr/catling#4]
Add types for things like:

- Functor
- Semigroup
- Monoid
- Monad

Etc.

**Comment by josephluck** [comment]
Gonna pick this up :tada:

**Comment by harrygr** [comment]
Semigroup and Monoid are defined. Would appreciate Monad and Functor types. No higher-kinded types in TS so they may be of limited value but we might be able to fake it.

**Comment by harrygr** [comment]
Here's something to think about:

```typescript
interface Functor<T> {
  map: <K>(fn: (a: T) => K) => ?
}
```
